# Generated by Django 3.1.2 on 2020-10-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='Profile'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
